/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

// ---------------------------------------------------------------------------
// Common models
// ---------------------------------------------------------------------------

export interface ModifiedAccessConditions {
  ifModifiedSince?: Date;
  ifUnmodifiedSince?: Date;
  ifMatch?: string;
  ifNoneMatch?: string;
}

export interface SourceModifiedAccessConditions {
  sourceIfMatch?: string;
  sourceIfNoneMatch?: string;
  sourceIfModifiedSince?: Date;
  sourceIfUnmodifiedSince?: Date;
}

export interface LeaseAccessConditions {
  leaseId?: string;
}

// ---------------------------------------------------------------------------
// Filesystem models
// ---------------------------------------------------------------------------

export interface FilesystemItem {
  name: string;
  lastModified: string;
  eTag: string;
}

export interface FilesystemListResponse {
  filesystems?: FilesystemItem[];
}

export interface FilesystemListOptionalParams {
  prefix?: string;
  continuation?: string;
  maxResults?: number;
}

export interface FilesystemCreateOptionalParams {
  properties?: string;
}

export interface FilesystemCreateResponse {
  statusCode: 201;
  eTag?: string;
  lastModified?: Date;
  namespaceEnabled?: string;
  requestId?: string;
  version?: string;
}

export interface FilesystemDeleteOptionalParams {
  modifiedAccessConditions?: ModifiedAccessConditions;
}

export interface FilesystemDeleteResponse {
  statusCode: 202;
  requestId?: string;
  version?: string;
}

export interface FilesystemGetPropertiesOptionalParams {
  // No optional params beyond standard headers
}

export interface FilesystemGetPropertiesResponse {
  statusCode: 200;
  eTag?: string;
  lastModified?: Date;
  properties?: string;
  namespaceEnabled?: string;
  requestId?: string;
  version?: string;
}

export interface FilesystemSetPropertiesOptionalParams {
  properties?: string;
  modifiedAccessConditions?: ModifiedAccessConditions;
}

export interface FilesystemSetPropertiesResponse {
  statusCode: 200;
  eTag?: string;
  lastModified?: Date;
  requestId?: string;
  version?: string;
}

export interface FilesystemListPathsOptionalParams {
  directory?: string;
  recursive?: boolean;
  continuation?: string;
  maxResults?: number;
  upn?: boolean;
}

// ---------------------------------------------------------------------------
// Path models
// ---------------------------------------------------------------------------

export type PathResourceType = "file" | "directory";

export interface PathItem {
  name: string;
  isDirectory?: boolean;
  lastModified: string;
  eTag?: string;
  contentLength?: number;
  owner?: string;
  group?: string;
  permissions?: string;
}

export interface PathListResponse {
  paths?: PathItem[];
}

export interface PathCreateOptionalParams {
  resource?: PathResourceType;
  continuation?: string;
  renameSource?: string;
  properties?: string;
  permissions?: string;
  umask?: string;
  leaseAccessConditions?: LeaseAccessConditions;
  modifiedAccessConditions?: ModifiedAccessConditions;
  sourceModifiedAccessConditions?: SourceModifiedAccessConditions;
}

export interface PathCreateResponse {
  statusCode: 201;
  eTag?: string;
  lastModified?: Date;
  continuation?: string;
  contentLength?: number;
  requestId?: string;
  version?: string;
}

export interface PathDeleteOptionalParams {
  recursive?: boolean;
  continuation?: string;
  leaseAccessConditions?: LeaseAccessConditions;
  modifiedAccessConditions?: ModifiedAccessConditions;
}

export interface PathDeleteResponse {
  statusCode: 200;
  continuation?: string;
  requestId?: string;
  version?: string;
}

export interface PathGetPropertiesOptionalParams {
  action?: "getAccessControl" | "getStatus";
  upn?: boolean;
  leaseAccessConditions?: LeaseAccessConditions;
  modifiedAccessConditions?: ModifiedAccessConditions;
}

export interface PathGetPropertiesResponse {
  statusCode: 200;
  eTag?: string;
  lastModified?: Date;
  resourceType?: string;
  properties?: string;
  owner?: string;
  group?: string;
  permissions?: string;
  acl?: string;
  leaseDuration?: string;
  leaseState?: string;
  leaseStatus?: string;
  contentLength?: number;
  contentType?: string;
  requestId?: string;
  version?: string;
}

export interface PathReadOptionalParams {
  range?: string;
  leaseAccessConditions?: LeaseAccessConditions;
  modifiedAccessConditions?: ModifiedAccessConditions;
}

export interface PathReadResponse {
  statusCode: 200;
  body?: NodeJS.ReadableStream;
  acceptRanges?: string;
  contentRange?: string;
  eTag?: string;
  lastModified?: Date;
  resourceType?: string;
  properties?: string;
  leaseDuration?: string;
  leaseState?: string;
  leaseStatus?: string;
  contentLength?: number;
  contentType?: string;
  requestId?: string;
  version?: string;
}

export type PathUpdateAction =
  | "append"
  | "flush"
  | "setAccessControl"
  | "setAccessControlRecursive"
  | "setProperties";

export type AclMode = "set" | "modify" | "remove";

export interface PathUpdateOptionalParams {
  action: PathUpdateAction;
  mode?: AclMode;
  position?: number;
  retainUncommittedData?: boolean;
  close?: boolean;
  contentLength?: number;
  contentMD5?: string;
  properties?: string;
  owner?: string;
  group?: string;
  permissions?: string;
  acl?: string;
  leaseAccessConditions?: LeaseAccessConditions;
  modifiedAccessConditions?: ModifiedAccessConditions;
  maxRecords?: number;
  continuation?: string;
}

export interface PathUpdateResponse {
  statusCode: 200 | 202;
  eTag?: string;
  lastModified?: Date;
  contentLength?: number;
  continuation?: string;
  requestId?: string;
  version?: string;
  // For setAccessControlRecursive
  directoriesSuccessful?: number;
  filesSuccessful?: number;
  failureCount?: number;
}

export type LeaseAction = "acquire" | "release" | "renew" | "break" | "change";

export interface PathLeaseOptionalParams {
  leaseAction: LeaseAction;
  leaseDuration?: number;
  leaseBreakPeriod?: number;
  leaseId?: string;
  proposedLeaseId?: string;
  modifiedAccessConditions?: ModifiedAccessConditions;
}

export interface PathLeaseResponse {
  statusCode: 200 | 201 | 202;
  eTag?: string;
  lastModified?: Date;
  leaseId?: string;
  leaseTime?: number;
  requestId?: string;
  version?: string;
}

// ---------------------------------------------------------------------------
// Error model
// ---------------------------------------------------------------------------

export interface StorageError {
  statusCode: number;
  code: string;
  message: string;
}
