/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

export enum DfsOperation {
  Filesystem_Create,
  Filesystem_Delete,
  Filesystem_GetProperties,
  Filesystem_SetProperties,
  Filesystem_List,
  Filesystem_ListPaths,
  Path_Create,
  Path_Delete,
  Path_GetProperties,
  Path_Read,
  Path_Update,
  Path_Lease,
}
export default DfsOperation;
