/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { DfsOperation } from "./operation";

/**
 * Specification for matching an incoming HTTP request to a DFS operation.
 * Used by the dispatch middleware to route requests.
 */
export interface IDfsOperationSpec {
  httpMethod: string;
  /** If true, the request must have a filesystem but no path in the URL. */
  filesystemOnly?: boolean;
  /** If true, the request must have both filesystem and path in the URL. */
  requiresPath?: boolean;
  /** Query parameters that must be present with specific values. */
  queryConditions?: { [key: string]: string | string[] | true };
  /** Headers that must be present (value = true means any value). */
  headerConditions?: { [key: string]: string | string[] | true };
}

/**
 * Dispatch specifications for all DFS operations.
 * The dispatch middleware iterates these and selects the best match.
 */
const Specifications: { [key: number]: IDfsOperationSpec } = {};

// ---- Filesystem operations ----

Specifications[DfsOperation.Filesystem_List] = {
  httpMethod: "GET",
  filesystemOnly: false,
  queryConditions: { resource: "account" }
};

Specifications[DfsOperation.Filesystem_Create] = {
  httpMethod: "PUT",
  filesystemOnly: true,
  queryConditions: { resource: "filesystem" }
};

Specifications[DfsOperation.Filesystem_Delete] = {
  httpMethod: "DELETE",
  filesystemOnly: true,
  queryConditions: { resource: "filesystem" }
};

Specifications[DfsOperation.Filesystem_GetProperties] = {
  httpMethod: "HEAD",
  filesystemOnly: true,
  queryConditions: { resource: "filesystem" }
};

Specifications[DfsOperation.Filesystem_SetProperties] = {
  httpMethod: "PATCH",
  filesystemOnly: true,
  queryConditions: { resource: "filesystem" }
};

Specifications[DfsOperation.Filesystem_ListPaths] = {
  httpMethod: "GET",
  filesystemOnly: true,
  queryConditions: { resource: "filesystem" }
};

// ---- Path operations ----

Specifications[DfsOperation.Path_Create] = {
  httpMethod: "PUT",
  requiresPath: true
};

Specifications[DfsOperation.Path_Delete] = {
  httpMethod: "DELETE",
  requiresPath: true
};

Specifications[DfsOperation.Path_GetProperties] = {
  httpMethod: "HEAD",
  requiresPath: true
};

Specifications[DfsOperation.Path_Read] = {
  httpMethod: "GET",
  requiresPath: true
};

Specifications[DfsOperation.Path_Update] = {
  httpMethod: "PATCH",
  requiresPath: true
};

Specifications[DfsOperation.Path_Lease] = {
  httpMethod: "POST",
  requiresPath: true,
  headerConditions: { "x-ms-lease-action": true }
};

export default Specifications;
