import * as assert from "assert";

import {
  operations,
  type OperationMetadata
} from "../../src/queue/typespecPilot/generated/operations";
import type { IServiceHandler } from "../../src/queue/typespecPilot/generated/handlers";

/**
 * This test imports artifacts generated by an internal pilot/prototype TypeSpec emitter
 * (`@azure-tools/typespec-azurite-emitter-pilot`, see companion PR Azure/typespec-azure#5614)
 * run against the **real, unchanged** Azure Storage Queue TypeSpec vendored into
 * `src/queue/typespecPilot/fixture/storage-queue-real/` (see that directory's `PROVENANCE.md`
 * for the exact source commit), plus a real `azurite.tsp` overlay citing Azurite's own
 * documented `swagger/queue.md` customizations. The files under
 * `src/queue/typespecPilot/generated` are copy-pasted, unmodified emitter output - nothing here
 * is hand-written. All 17 real Queue operations (`Service` + `Queue` interfaces, flattened into
 * one `IServiceHandler`) are generated with zero diagnostics and zero skipped operations.
 *
 * The goal is to prove the generated artifacts compile under Azurite's own TypeScript toolchain
 * and carry the structural information this repo's real dispatcher/handler boundary relies on,
 * comparing against:
 *  - src/queue/generated/middleware/dispatch.middleware.ts (`isRequestAgainstOperation`), which
 *    matches requests using HTTP method, URL path template, and required query/header parameters.
 *  - src/queue/generated/artifacts/parameters.ts / specifications.ts, whose `mapper.required` /
 *    `serializedName` fields are what the dispatcher reads per parameter.
 *  - src/queue/generated/handlers/IQueueHandler.ts, whose methods take
 *    `(options, context) => Promise<Response>`.
 *  - src/queue/generated/Context.ts, the per-request context object handlers receive.
 */
describe("TypeSpec emitter pilot generated artifacts (real Storage Queue spec) @loki", () => {
  function findOperation(name: string): OperationMetadata {
    const op = operations.find((candidate) => candidate.name === name);
    assert.ok(op, `expected a generated operation named "${name}"`);
    return op!;
  }

  it("generates exactly the 17 real Queue operations, zero skipped", () => {
    assert.strictEqual(operations.length, 17);
  });

  it("generates route metadata with the method + path a dispatcher needs", () => {
    const create = findOperation("Create");
    assert.strictEqual(create.verb, "put");
    assert.strictEqual(create.path, "/");

    const sendMessage = findOperation("SendMessage");
    assert.strictEqual(sendMessage.verb, "post");
    assert.strictEqual(sendMessage.path, "/messages");
  });

  it("marks the GET operation's query parameters with name/location/required, as dispatch.middleware.ts needs", () => {
    const receiveMessages = findOperation("ReceiveMessages");

    const numberOfMessages = receiveMessages.parameters.find(
      (p) => p.name === "numberOfMessages"
    );
    assert.ok(numberOfMessages, "expected a numberOfMessages query parameter");
    assert.strictEqual(numberOfMessages!.location, "query");
    assert.strictEqual(numberOfMessages!.wireName, "numofmessages");
    assert.strictEqual(
      numberOfMessages!.required,
      false,
      "optional query parameters must not be marked required, or a dispatcher would wrongly reject requests omitting them"
    );

    const messageId = findOperation("UpdateMessage").parameters.find(
      (p) => p.name === "messageId"
    );
    assert.ok(messageId, "expected a messageId path parameter");
    assert.strictEqual(messageId!.location, "path");
    assert.strictEqual(
      messageId!.required,
      true,
      "path parameters are always required for a dispatcher to match a URL template"
    );
  });

  it("captures the custom response header's name/wire name mapping in per-status response metadata", () => {
    const queueGetProperties = findOperation("QueueGetProperties");
    const okResponse = queueGetProperties.responses.find(
      (r) => r.statusCode === 200
    )!;
    assert.deepStrictEqual(
      okResponse.headers.find((h) => h.name === "approximateMessagesCount"),
      {
        name: "approximateMessagesCount",
        wireName: "x-ms-approximate-messages-count"
      }
    );
  });

  it("captures the POST operation's XML request body content type (the real spec's declared wire format)", () => {
    const sendMessage = findOperation("SendMessage");
    assert.strictEqual(sendMessage.hasRequestBody, true);
    assert.deepStrictEqual(sendMessage.requestBodyContentTypes, [
      "application/xml"
    ]);
  });

  it("applies the azurite.tsp overlay's @@doc override to the generated handler's doc comment", () => {
    // azurite.tsp's @@doc override on Queue.sendMessage (see fixture/storage-queue-real/azurite.tsp)
    // must show up in the generated handler's method doc comment, proving the overlay pattern - a
    // separate file layering non-breaking metadata onto an unchanged base spec - actually took
    // effect against the real spec, not just a toy fixture.
    const handlersSource = require("fs").readFileSync(
      require.resolve("../../src/queue/typespecPilot/generated/handlers"),
      "utf8"
    ) as string;
    assert.ok(
      handlersSource.includes(
        "Azurite note: the emulator enforces the same relaxed"
      ),
      "expected the azurite.tsp overlay's @@doc override to appear in generated handlers.ts"
    );
  });

  it("generates a handler interface whose method shape matches IQueueHandler's (params, context) => Promise<Response> convention", () => {
    // Type-only check: this doesn't execute, but `tsc`/`ts-node` will fail to compile the test
    // file (and therefore fail this test run) if IServiceHandler's method signatures don't
    // accept a trailing context argument and return a Promise, matching
    // src/queue/generated/handlers/IQueueHandler.ts's real calling convention.
    const assertHandlerShape = (handler: IServiceHandler) => {
      const createResult: Promise<unknown> = handler.create(
        { version: "2025-05-05" },
        { contextId: "ctx" }
      );
      const sendMessageResult: Promise<unknown> = handler.sendMessage(
        {
          contentType: "application/xml",
          version: "2025-05-05",
          body: { messageText: "hi" }
        },
        { contextId: "ctx" }
      );
      return [createResult, sendMessageResult];
    };
    assert.strictEqual(typeof assertHandlerShape, "function");
  });

  it("documents the real gap this vendoring surfaced: queueName is client-scoped, not an operation parameter", () => {
    // The real Storage Queue TypeSpec routes {queueName} through the client's own base URL
    // (QueueClient initialization, a TCGC @clientInitialization concept) rather than as an HTTP
    // operation path/query parameter - so it is absent from every queue-scoped operation's
    // generated parameter list. A dispatcher built purely from this metadata cannot recover which
    // operations are queue-scoped without an additional, hand-written classification (see
    // `server/pilotDispatchMiddleware.ts`'s `OPERATION_DISPATCH_PATTERN`, which maps each
    // operation directly onto the same `"/" | "/queue" | "/queue/messages" |
    // "/queue/messages/messageId"` bucket that Azurite's own real, unmodified
    // `queueStorageContextMiddleware` already computes for every request today - confirming this
    // is an inherent property of Azure Storage's URL shape, not a shortcoming unique to this
    // emitter). This test pins down that absence so it can't silently regress-fixed without
    // updating that documented workaround.
    const create = findOperation("Create");
    assert.strictEqual(
      create.parameters.some((p) => p.name === "queueName"),
      false,
      "expected no queueName parameter in the generated metadata for a queue-scoped operation"
    );
  });
});
