import * as assert from "assert";

import {
  operations,
  type OperationMetadata,
} from "../../typespec-emitter-pilot/generated/operations";
import type { IServiceHandler } from "../../typespec-emitter-pilot/generated/handlers";

/**
 * This test imports artifacts generated by an internal pilot/prototype TypeSpec emitter
 * (`@azure-tools/typespec-azurite-emitter-pilot`, see companion PR Azure/typespec-azure#5614)
 * run against a small toy "Queue-like" fixture. The files under `typespec-emitter-pilot/generated`
 * are copy-pasted, unmodified emitter output — nothing here is hand-written.
 *
 * The goal is *not* to validate real Azure Storage Queue behavior (the fixture is a toy slice),
 * but to prove the generated artifacts compile under Azurite's own TypeScript toolchain and carry
 * the structural information this repo's real dispatcher/handler boundary relies on, comparing
 * against:
 *  - src/queue/generated/middleware/dispatch.middleware.ts (`isRequestAgainstOperation`), which
 *    matches requests using HTTP method, URL path template, and required query/header parameters.
 *  - src/queue/generated/artifacts/parameters.ts / specifications.ts, whose `mapper.required` /
 *    `serializedName` fields are what the dispatcher reads per parameter.
 *  - src/queue/generated/handlers/IQueueHandler.ts, whose methods take
 *    `(options, context) => Promise<Response>`.
 *  - src/queue/generated/Context.ts, the per-request context object handlers receive.
 */
describe("TypeSpec emitter pilot generated artifacts @loki", () => {
  function findOperation(name: string): OperationMetadata {
    const op = operations.find((candidate) => candidate.name === name);
    assert.ok(op, `expected a generated operation named "${name}"`);
    return op!;
  }

  it("generates route metadata with the method + path a dispatcher needs", () => {
    const createQueue = findOperation("CreateQueue");
    assert.strictEqual(createQueue.verb, "put");
    assert.strictEqual(createQueue.path, "/{queueName}");

    const listMessages = findOperation("ListMessages");
    assert.strictEqual(listMessages.verb, "get");
    assert.strictEqual(listMessages.path, "/{queueName}/messages");
  });

  it("marks the GET operation's query parameters with name/location/required, as dispatch.middleware.ts needs", () => {
    const listMessages = findOperation("ListMessages");

    const numOfMessages = listMessages.parameters.find((p) => p.name === "numOfMessages");
    assert.ok(numOfMessages, "expected a numOfMessages query parameter");
    assert.strictEqual(numOfMessages!.location, "query");
    assert.strictEqual(numOfMessages!.wireName, "numOfMessages");
    assert.strictEqual(
      numOfMessages!.required,
      false,
      "optional query parameters must not be marked required, or a dispatcher would wrongly reject requests omitting them",
    );

    const queueName = listMessages.parameters.find((p) => p.name === "queueName");
    assert.ok(queueName, "expected a queueName path parameter");
    assert.strictEqual(queueName!.location, "path");
    assert.strictEqual(
      queueName!.required,
      true,
      "path parameters are always required for a dispatcher to match a URL template",
    );
  });

  it("captures the custom response header's name/wire name mapping in per-status response metadata", () => {
    const getQueueProperties = findOperation("GetQueueProperties");
    assert.strictEqual(getQueueProperties.responses.length, 1);
    const [response] = getQueueProperties.responses;
    assert.strictEqual(response.statusCode, 200);
    assert.deepStrictEqual(response.headers, [
      { name: "approximateMessagesCount", wireName: "x-ms-approximate-messages-count" },
    ]);
  });

  it("captures the PUT operation's JSON request body content type", () => {
    const createQueue = findOperation("CreateQueue");
    assert.strictEqual(createQueue.hasRequestBody, true);
    assert.deepStrictEqual(createQueue.requestBodyContentTypes, ["application/json"]);
  });

  it("generates a handler interface whose method shape matches IQueueHandler's (params, context) => Promise<Response> convention", () => {
    // Type-only check: this doesn't execute, but `tsc`/`ts-node` will fail to compile the test
    // file (and therefore fail this test run) if IServiceHandler's method signatures don't
    // accept a trailing context argument and return a Promise, matching
    // src/queue/generated/handlers/IQueueHandler.ts's real calling convention.
    const assertHandlerShape = (handler: IServiceHandler) => {
      const createQueueResult: Promise<unknown> = handler.createQueue(
        { queueName: "q", body: { description: "d" } },
        { contextId: "ctx" },
      );
      const listMessagesResult: Promise<unknown> = handler.listMessages(
        { queueName: "q" },
        { contextId: "ctx" },
      );
      return [createQueueResult, listMessagesResult];
    };
    assert.strictEqual(typeof assertHandlerShape, "function");
  });

  it("generates exactly the three operations present in the toy fixture", () => {
    assert.deepStrictEqual(
      operations.map((op) => op.name).sort(),
      ["CreateQueue", "GetQueueProperties", "ListMessages"],
    );
  });
});
