import { Router, type Request, type Response } from "express";
import { randomUUID } from "node:crypto";

import type { Context, IServiceHandler } from "../generated/handlers";
import type { OperationMetadata } from "../generated/operations";
import { operations } from "../generated/operations";

/**
 * Parameters whose generated TS type is `number` rather than `string`. The dispatch metadata
 * emitted by the pilot emitter (`OperationParameterBinding`) intentionally only carries what a
 * dispatcher needs to match/extract a request (wire name, location, required-ness) - not full
 * type information, so coercing a raw string query/header value into the right JS type is left
 * as a handler-boundary concern, the same way a typed router layer normally works. Hardcoded
 * here for the pilot's two numeric query parameters; a richer emitter could emit a `type` tag on
 * `OperationParameterBinding` to make this generic, noted as follow-up work in the README.
 */
const NUMERIC_PARAMETER_NAMES = new Set(["numOfMessages", "visibilityTimeout"]);

type HandlerMethod = (params: unknown, context: Context) => Promise<HandlerResult>;

interface HandlerResult {
  statusCode: number;
  headers?: Record<string, unknown>;
  body?: unknown;
}

/** Converts a TypeSpec-style route template (e.g. `/{queueName}/messages`) into an Express path (`/:queueName/messages`). */
function toExpressPath(path: string): string {
  return path.replace(/\{(\w+)\}/g, ":$1");
}

/**
 * Operation names are PascalCase (e.g. `"CreateQueue"`); handler methods are camelCase (e.g.
 * `createQueue`) - the same convention the pilot emitter's `render-handlers.ts` uses to derive
 * `IServiceHandler` method names from `ServerOperation.name`, duplicated here since this is
 * hand-written glue code, not generated.
 */
function handlerMethodName(operationName: string): string {
  return operationName[0].toLowerCase() + operationName.slice(1);
}

function readParameter(
  req: Request,
  binding: OperationMetadata["parameters"][number],
): string | undefined {
  switch (binding.location) {
    case "path": {
      const value = req.params[binding.name];
      return typeof value === "string" ? value : undefined;
    }
    case "query": {
      const value = req.query[binding.wireName];
      return typeof value === "string" ? value : undefined;
    }
    case "header":
      return req.header(binding.wireName);
    default:
      return undefined;
  }
}

/**
 * Translates a handler's typed result (`{ statusCode, headers, body }`, shaped like the
 * generated `XxxResponse` union) into a real Express HTTP response, using the generated
 * per-status `OperationResponseMetadata` to map each typed `headers` property (e.g.
 * `approximateMessagesCount`) back to its real wire header name (e.g.
 * `x-ms-approximate-messages-count`).
 */
function applyResponse(res: Response, operation: OperationMetadata, result: HandlerResult): void {
  const responseMetadata = operation.responses.find((r) => r.statusCode === result.statusCode);
  res.status(result.statusCode);
  if (result.headers && responseMetadata) {
    const headers = result.headers;
    for (const headerBinding of responseMetadata.headers) {
      const value = headers[headerBinding.name];
      if (value !== undefined) {
        res.setHeader(headerBinding.wireName, String(value));
      }
    }
  }
  if (result.body !== undefined) {
    res.json(result.body);
  } else {
    res.end();
  }
}

/**
 * A hand-written Express dispatcher that builds real HTTP routes directly from the pilot
 * emitter's generated `operations` metadata table (`typespec-emitter-pilot/generated/
 * operations.ts`), and binds each route to the matching method on a hand-written
 * `IServiceHandler` implementation. Analogous in spirit to Azurite's real generated dispatcher
 * (`src/queue/generated/middleware/dispatch.middleware.ts`'s `isRequestAgainstOperation`), which
 * matches requests against AutoRest-generated `OperationSpec`s and invokes the matching
 * hand-written `IQueueHandler` method - except here the metadata table itself is generated by
 * the TypeSpec pilot emitter instead of AutoRest. This is the piece that proves the generated
 * contract is actually load-bearing: real HTTP requests are routed and parameter-bound purely
 * from `operations` metadata, not from hand-written route strings.
 */
export function createPilotRouter(handler: IServiceHandler): Router {
  const router = Router();

  for (const operation of operations) {
    const method = operation.verb as "get" | "put" | "post" | "patch" | "delete" | "head";
    router[method](toExpressPath(operation.path), (req: Request, res: Response) => {
      void (async () => {
        try {
          const params: Record<string, unknown> = {};
          for (const binding of operation.parameters) {
            const rawValue = readParameter(req, binding);
            if (binding.required && rawValue === undefined) {
              res.status(400).json({
                error: `Missing required ${binding.location} parameter "${binding.wireName}"`,
              });
              return;
            }
            if (rawValue !== undefined) {
              params[binding.name] = NUMERIC_PARAMETER_NAMES.has(binding.name)
                ? Number(rawValue)
                : rawValue;
            }
          }
          if (operation.hasRequestBody) {
            params.body = req.body;
          }

          const context: Context = { contextId: randomUUID() };
          const boundMethod = (handler as unknown as Record<string, HandlerMethod>)[
            handlerMethodName(operation.name)
          ];
          const result = await boundMethod.call(handler, params, context);

          applyResponse(res, operation, result);
        } catch (error) {
          res
            .status(500)
            .json({ error: error instanceof Error ? error.message : String(error) });
        }
      })();
    });
  }

  return router;
}
