/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { DfsOperation } from "../artifacts/operation";

export interface IHandlerPath {
  handler: string;
  method: string;
  arguments: string[];
}

const operationHandlerMapping: { [key: number]: IHandlerPath } = {};

operationHandlerMapping[DfsOperation.Filesystem_Create] = {
  arguments: ["options"],
  handler: "filesystemHandler",
  method: "create"
};
operationHandlerMapping[DfsOperation.Filesystem_Delete] = {
  arguments: ["options"],
  handler: "filesystemHandler",
  method: "delete"
};
operationHandlerMapping[DfsOperation.Filesystem_GetProperties] = {
  arguments: ["options"],
  handler: "filesystemHandler",
  method: "getProperties"
};
operationHandlerMapping[DfsOperation.Filesystem_SetProperties] = {
  arguments: ["options"],
  handler: "filesystemHandler",
  method: "setProperties"
};
operationHandlerMapping[DfsOperation.Filesystem_List] = {
  arguments: ["options"],
  handler: "filesystemHandler",
  method: "list"
};
operationHandlerMapping[DfsOperation.Filesystem_ListPaths] = {
  arguments: ["options"],
  handler: "filesystemHandler",
  method: "listPaths"
};
operationHandlerMapping[DfsOperation.Path_Create] = {
  arguments: ["body", "options"],
  handler: "pathHandler",
  method: "create"
};
operationHandlerMapping[DfsOperation.Path_Delete] = {
  arguments: ["options"],
  handler: "pathHandler",
  method: "delete"
};
operationHandlerMapping[DfsOperation.Path_GetProperties] = {
  arguments: ["options"],
  handler: "pathHandler",
  method: "getProperties"
};
operationHandlerMapping[DfsOperation.Path_Read] = {
  arguments: ["options"],
  handler: "pathHandler",
  method: "read"
};
operationHandlerMapping[DfsOperation.Path_Update] = {
  arguments: ["body", "options"],
  handler: "pathHandler",
  method: "update"
};
operationHandlerMapping[DfsOperation.Path_Lease] = {
  arguments: ["options"],
  handler: "pathHandler",
  method: "lease"
};

export function getHandlerByOperation(
  operation: DfsOperation
): IHandlerPath | undefined {
  return operationHandlerMapping[operation];
}

export default operationHandlerMapping;
