/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as DfsModels from "../artifacts/models";
import Context from "../Context";

export default interface IFilesystemHandler {
  create(
    options: DfsModels.FilesystemCreateOptionalParams,
    context: Context
  ): Promise<DfsModels.FilesystemCreateResponse>;

  delete(
    options: DfsModels.FilesystemDeleteOptionalParams,
    context: Context
  ): Promise<DfsModels.FilesystemDeleteResponse>;

  getProperties(
    options: DfsModels.FilesystemGetPropertiesOptionalParams,
    context: Context
  ): Promise<DfsModels.FilesystemGetPropertiesResponse>;

  setProperties(
    options: DfsModels.FilesystemSetPropertiesOptionalParams,
    context: Context
  ): Promise<DfsModels.FilesystemSetPropertiesResponse>;

  list(
    options: DfsModels.FilesystemListOptionalParams,
    context: Context
  ): Promise<DfsModels.FilesystemListResponse>;

  listPaths(
    options: DfsModels.FilesystemListPathsOptionalParams,
    context: Context
  ): Promise<DfsModels.PathListResponse>;
}
