/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import IFilesystemHandler from "./IFilesystemHandler";
import IPathHandler from "./IPathHandler";

export interface IDfsHandlers {
  filesystemHandler: IFilesystemHandler;
  pathHandler: IPathHandler;
}
export default IDfsHandlers;
