/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as DfsModels from "../artifacts/models";
import Context from "../Context";

export default interface IPathHandler {
  create(
    body: NodeJS.ReadableStream | undefined,
    options: DfsModels.PathCreateOptionalParams,
    context: Context
  ): Promise<DfsModels.PathCreateResponse>;

  delete(
    options: DfsModels.PathDeleteOptionalParams,
    context: Context
  ): Promise<DfsModels.PathDeleteResponse>;

  getProperties(
    options: DfsModels.PathGetPropertiesOptionalParams,
    context: Context
  ): Promise<DfsModels.PathGetPropertiesResponse>;

  read(
    options: DfsModels.PathReadOptionalParams,
    context: Context
  ): Promise<DfsModels.PathReadResponse>;

  update(
    body: NodeJS.ReadableStream | undefined,
    options: DfsModels.PathUpdateOptionalParams,
    context: Context
  ): Promise<DfsModels.PathUpdateResponse>;

  lease(
    options: DfsModels.PathLeaseOptionalParams,
    context: Context
  ): Promise<DfsModels.PathLeaseResponse>;
}
